### ISSUE TITLE
Run "menu" shows build tags (1) when there are none

### ISSUE THREAD

**Issue by myitcv** [dave/play#3]
Rough steps to reproduce:

* create a play example
* add a build tag
* build
* remove the build tag
* observe the menu still thinks there's a build tag

<img width="537" alt="screen shot 2018-05-08 at 17 43 41" src="https://user-images.githubusercontent.com/3374574/39770708-b04c6cf4-52e7-11e8-83e9-61701e0c4e02.png">

**Comment by dave** [comment]
Thanks! Should be fixed by https://github.com/dave/play/commit/3359b43ad60331af5a6feb2c92dc56ab3ac3a52a
