### ISSUE TITLE
The vertical bar is too sticky

### ISSUE THREAD

**Issue by hajimehoshi** [dave/play#5]
1. Open https://play.jsgo.io/github.com/hajimehoshi/ebiten/examples/minify
2. Try to drag & drop the vertical bar between the code snippet and the result view.

I found it was impossible to release the bar by clicking. I tested this on Chrome Version 68.0.3440.75 on macOS 10.13.6 (17G2208).

**Comment by hajimehoshi** [comment]
friendly ping

**Comment by dave** [comment]
Thanks for this... Won't have any time to take a look for a while...

**Comment by dave** [comment]
Hey sorry about the delay... I think that's fixed now... Let me know if you have any more problems.

**Comment by hajimehoshi** [comment]
Thank you for fixing this!
